Additional conditions
WeaponMechanics/MechanicsMain pull request #249
Opened 2023-02-11 13:23 UTC by Vierdant

**Desc:**
Added new conditions that I personally would use.

**HasPermission**
Checks if the target (player) has a permission node

Example: `?HasPermission{permission=essentials.god}`

**OnBlock**
Checks if the target is standing on a specific block (multiple blocks can be provided)

Example: `?OnBlock{blocks=DIRT}`

Multi-block example: `?OnBlock{blocks=DIRT,STONE,GRAVEL}`

**OnGround**
A simple condition that checks if the target is standing on solid ground

Example: `?OnGround{}`

**Outside**
A simple condition that checks if the target is outside in the open, as in the sky is above them, not a block.

Example: `?Outside{}`

**MythicMobsFactionCondition** - **Requires mythic mobs**
Checks if the target entity is of a provided faction

Example: `?MythicMobsFaction{faction=monsters}`

2023-02-12 18:30 UTC, CJCrafter commented on MechanicsCore/src/main/java/me/deecaad/core/mechanics/conditions/HasPermissionCondition.java
> +        if (!(target instanceof Player)) return false;
This check should be removed

2023-02-12 18:32 UTC, CJCrafter commented on MechanicsCore/src/main/java/me/deecaad/core/mechanics/conditions/MythicMobsFactionCondition.java
> +        if (target instanceof Player) {
You should be using the [enhanced instanceof](https://www.baeldung.com/java-pattern-matching-instanceof#pattern-matching) from Java 14

2023-02-12 18:35 UTC, CJCrafter commented on MechanicsCore/src/main/java/me/deecaad/core/mechanics/conditions/OnGroundCondition.java
> +public class OnGroundCondition extends Condition {
`OnBlock` and `OnGround` need to be merged... less clutter on the wiki.

Imagine
```yaml
Mechanics:
  - "?OnGround{}"  # Checks if the entity is on the ground
  - "?OnGround{blocks=[DIRT, GRAVEL]}"  # Checks if the entity is on the ground AND that block is dirt or gravel. 
```

2023-02-12 18:39 UTC, CJCrafter requested changes
Thanks for contributing! Your changes look pretty good, but I left a few comments before I can merge them.

2023-02-12 18:39 UTC, CJCrafter commented on MechanicsCore/src/main/java/me/deecaad/core/mechanics/conditions/OutsideCondition.java
> +public class OutsideCondition extends Condition {
Have to reject this one... This is already done and more efficient by using the [LightLevelCondition](https://github.com/WeaponMechanics/MechanicsMain/wiki/LightLevelCondition) and making sure it is 16 (maximum light)

2023-02-12 18:39 UTC, CJCrafter commented on MechanicsCore/src/main/java/me/deecaad/core/mechanics/conditions/MythicMobsFactionCondition.java
> +        if (target instanceof Player) {
You should be using the [enhanced instanceof](https://www.baeldung.com/java-pattern-matching-instanceof#pattern-matching) from Java 14

2023-02-13 13:25 UTC, Vierdant commented
Requested changes implemented! Removed unnecessary conditions and improved the code.

2023-02-13 17:15 UTC, CJCrafter approved these changes
Looks good! I'll make a wiki for each page then get this merged. Thanks for contributing

2023-02-15 15:44 UTC, merged