Relative Skins (+Attachments)
WeaponMechanics/MechanicsMain pull request #341
Opened 2023-07-21 22:35 UTC by CJCrafter

The old skin system code is quite statically typed. This PR adds an interface for both skins and skin selectors. This allows us to add relative skins that simplify the config, especially when using skins and attachments to modify the weapon skin.

2023-07-21 22:36 UTC, CJCrafter commented
The new resource pack and config will break all users who still use an old version of the plugin.

2023-07-22 16:04 UTC, DeeCaaD requested changes
1) Because of the relative skins, you'll probably have to make serializers check that any combination of weapon A skins does not overlap with any combination of weapon B skins. This is pretty big QOL thing, which is easier to implement as code rather than having confused users

2) CS + CSP converter to support new format

2023-07-22 16:30 UTC, CJCrafter commented on WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/weapon/skin/RelativeSkinSelector.java
> +                // cannot access the WMP API, so users may be prone to error
In the future, a WMP manual check is possible.

2023-07-22 16:35 UTC, CJCrafter commented on WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/weapon/skin/RelativeSkinSelector.java
> +                // cannot access the WMP API, so users may be prone to error
No need to update CS+CSP converter, old format still works (+new format is so comparatively "weird" that a perfect converter is not possible).

But adding a "strict format" mode for relative skins is probably a good idea. Basically I have this formula that I like which allows 999 custom weapons, each with 10 options for reloading/scoping/scope stacking/sprinting skins, each with 10 options for WMC `/skin` skins, each with room for 5 attachments "slots" (each attachment slot can have 10 mutually exclusive attachments, so 10 different scopes, for example).

Forcing players to use this format (but being able to turn it off in `config.yml` is a very good idea). A youtube video explaining relative skins in better detail is definitely coming soon.

2023-07-23 04:06 UTC, CJCrafter commented
https://github.com/WeaponMechanics/MechanicsMain/pull/341/files?file-filters%5B%5D=.yml&show-deleted-files=true&show-viewed-files=true

^ link to view config changes

2023-07-23 04:08 UTC, CJCrafter commented on WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/weapon/skin/RelativeSkinSelector.java
> +                // cannot access the WMP API, so users may be prone to error
Added: https://github.com/WeaponMechanics/MechanicsMain/pull/341/commits/dc3f4bd6781f4fc2b77aff4eae5ee671da88142c#diff-9f9758eb4521c500c72c11dc6dad08a8cae4ea547e645c9c1f7b9da2215659f9R54-R121

2023-07-23 20:22 UTC, merged