Add Repair only broken Weapon and Consume on Use RepairKit
WeaponMechanics/MechanicsMain pull request #353
Opened 2023-08-22 19:30 UTC by thierryboiago

- added setting to use repair only when weapon is broken.
- has been added so when repair kit is used it disappears regardless of durability

2023-08-22 19:31 UTC, thierryboiago commented
![image](https://github.com/WeaponMechanics/MechanicsMain/assets/58778448/9beff803-f119-436a-87f0-2e27e7677759)

2023-08-23 17:58 UTC, CJCrafter requested changes

2023-08-23 17:58 UTC, CJCrafter commented on WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/listeners/RepairItemListener.java
> +            }else{
We use oracle conventions in the WeaponMechanics repo `}else{` -> `} else {`

2023-08-23 17:58 UTC, CJCrafter commented on WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/listeners/RepairItemListener.java
> +            if(kit.consumeOnUse){
if (kit.consumeOnUse) {

2023-08-23 17:58 UTC, CJCrafter commented on WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/listeners/RepairItemListener.java
> +        private boolean consumeOnUse;
blank line before javadoc comments

2023-08-23 17:58 UTC, CJCrafter commented on WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/listeners/RepairItemListener.java
> +                if (customDurability.isRepairOnlyBroken()){
if (customDurability.isRepairOnlyBroken()) {

2023-08-24 20:02 UTC, CJCrafter approved these changes
Looks good!

2023-10-14 01:29 UTC, merged