Add support for the crawling animation.
WeaponMechanics/MechanicsMain pull request #385
Opened 2024-01-02 09:44 UTC by ShakyTimon

Hey, in my commit I added support for the crawling animation in Minecraft, and considering there is not native methods to check for this, I used the process of elimination, and the height of your hitbox. If you're not sneaking, swimming, or gliding, but have a reduced hitbox height, you are 'crawling'.

I struggled to build WeaponMechanics due to authentication being required for a dependency:
```> Could not get resource 'https://maven.pkg.github.com/WeaponMechanics/MechanicsAutoDownload/me/cjcrafter/mechanicsautodownload/1.3.1/mechanicsautodownload-1.3.1.pom'. Received status code 401 from server: Unauthorized.```

If this is an issue on my side, I would much appreciate some help.

I did however test what I added to EntityWrapper inside my own plugin, source:

```
    @Override
    public boolean onCommand(CommandSender commandSender, org.bukkit.command.Command command, String s, String[] strings) {
        Player player = (Player) commandSender;

        if (player.isSneaking()) {
            player.sendMessage("You are sneaking.");
            return true;
        }
        if (player.isSwimming()) {
            player.sendMessage("You are swimming.");
            return true;
        }
        if (player.isGliding()) {
            player.sendMessage("You are gliding.");
            return true;
        }

        final double crawlingMaxHeight = 1.5;
        double hitboxHeight = player.getBoundingBox().getHeight();
        if (hitboxHeight <= crawlingMaxHeight) {
            player.sendMessage("You are crawling.");
        } else {
            player.sendMessage("You are not crawling.");
        }
        return true;
    }
```
Here's what that looked like: https://cdn.discordapp.com/attachments/1128569715976065054/1191678119753560124/170418859513897991.mp4?ex=65a64fbc&is=6593dabc&hm=cd1e203f954fd4a1deab397fae174cf05eda80b8e0122e5b9709e70a2fe196c1&

This is my first PR to a large project so I hope that everything is okay,

2024-01-03 18:02 UTC, CJCrafter requested changes
Just a minor change

Thanks very much for contributing! :)

2024-01-03 18:31 UTC, ShakyTimon commented on WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/wrappers/EntityWrapper.java
> +    public boolean isCrawling() {
I've implemented it, please check, and if everything is okay, merge it.

As for the scripts, please don't include those in the merge, they were very buggy, untested, and 'quick' rewrites.

2024-01-03 20:55 UTC, CJCrafter commented
You should revert those script changes then

2024-01-04 02:46 UTC, ShakyTimon commented
> You should revert those script changes then

After some tinkering with git; done.

2024-01-04 17:10 UTC, CJCrafter approved these changes

2024-01-04 19:46 UTC, merged

2024-01-04 20:16 UTC, CJCrafter commented
Thanks for contributing :+1: